server:
  port: 8999
  additionalPort: 8001,8002
  servlet:
    context-path: /ums-api

spring:
  application:
    name: ums-api
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:postgresql://localhost:15432/postgres?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
        username: postgres
        password: postgres
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT version()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#  messages:
#    basename: classpath:i18n/messages/messages                                      #国际化配置
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: noreply-dev@bieases.com
#    password: dpkmvczkpwmqjzoj
#    properties.mail.smtp:
#      auth: true
#      starttls.enable: true
#      ssl.trust: smtp.gmail.com
  liquibase:
    change-log: classpath:/liquibase/changelog/master.xml
  autoconfigure:
    #过滤druid自动装配
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #数据源配置
#  redis:
#    # 地址
#    host: 69.231.169.19
#    # 端口，默认为6379
#    port: 16379
#    # 数据库索引
#    database: 0
#    # 密码
#    password: SvweoFlWXaem0Xk
#    # 连接超时时间
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms

swagger2:
  termsOfServiceUrl: localhost:${server.port}
  description: ${spring.application.name}-swagger2-api
  title: ${spring.application.name}-swagger2-api
  version: 1.0
  name: ${spring.application.name}
  url: localhost:${server.port}
  email: 149906878@qq.comw
  enable: true
mybatis-plus:
  type-aliases-package: com.suchusa.biease.core.entity                            #配置mybatis扫描的entity包
  global-config:
    db-column-underline: false                                                      #驼峰下划线转换
    refresh-mapper: true                                                            #刷新mapper 调试神器
    db-config:                                                                      #开始配置逻辑删除
      update-strategy: NOT_EMPTY                                                    #update方法更新数据时过滤null和空字符串(默认NOT_NULL)
      logic-delete-field: deleted                                                   # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1                                                         # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0                                                     # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true                                              #自定义SQL注入器
    cache-enabled: false                                                            #配置的缓存的全局开关
    lazyLoadingEnabled: true                                                        #延时加载的开关
    multipleResultSetsEnabled: true                                                 #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    safe-result-handler-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl                           #sql日志，如果不想打印，请注释
    mapper-locations: classpath:mapper/*.xml                                        #配置mybatis的mapper配置的xml文件

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz123456abcdefghijklmnopqrstuvwxyz123456abcdefghijklmnopqrstuvwxyz123456abcdefghijklmnopqrstuvwxyz123456abcdefghijklmnopqrstuvwxyz123456abcdefghijklmnopqrstuvwxyz123456
  # 令牌有效期（默认15分钟）
  expireTime: 6000000
  # Jwt Token 校验开关(0-开启；1-关闭)
  flag: 1

interceptor:
  #默认开关为true
  switch:
    #OPT拦截器开关
    otp: true
    #防重复提交开关
    repeatSubmit: false
    #登录Token校验开关
    loginToken: true
    #签名+防重放
    sign: false
    #Bieases 响应报文签名开关
    bieasesSign: false
knife4j:
  # 开启增强配置
  enable: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: 123456
asynThreadPool:
  #异步线程池
  corePoolSize: 2
  maximumPoolSize: 4
  keepAliveTime: 60

logging:
  config: classpath:logback-spring.xml
  file:
    path: /Users/leif/IdeaProjects/ums/logs
  pattern:
    level: INFO